const THEMES = [
  {
    name: "light",
    label: "Light",
    dark: false,
    color: "#000000",
    secondary: "#9ca3af",
    background: "#ffffff",
    star: "#eab308",
    tab: "#bfdbfe",
  },
  {
    name: "dark",
    label: "Dark",
    dark: true,
    color: "#ffffff",
    secondary: "#9ca3af",
    background: "#000000",
    star: "#fde047",
    tab: "#1e40af",
  },
  {
    name: "dim",
    label: "Dim",
    dark: true,
    color: "#ffffff",
    secondary: "#9ca3af",
    background: "#1f2937",
    star: "#fde047",
    tab: "#1e40af",
  },
  {
    name: "pink",
    label: "Pink",
    dark: false,
    color: "#000000",
    secondary: "#475569",
    background: "#fbcfe8",
    star: "#000000",
    tab: "#bfdbfe",
  },
  {
    name: "hacker",
    label: "Hacker",
    dark: true,
    color: "#bef264",
    secondary: "#65a30d",
    background: "#000000",
    star: "#bef264",
    tab: "#1e40af",
  },
  {
    name: "purple",
    label: "Purple",
    dark: true,
    color: "#ede9fe",
    secondary: "#c4b5fd",
    background: "#5b21b6",
    star: "#ede9fe",
    tab: "#5b21b6",
  },
  {
    name: "silver",
    label: "Silver",
    dark: false,
    color: "#000000",
    secondary: "#475569",
    background: "#e2e8f0",
    star: "#475569",
    tab: "#bfdbfe",
  },
  {
    name: "trans",
    label: "Trans",
    dark: false,
    color: "#000000",
    secondary: "#9ca3af",
    background: "#ffffff",
    star: "#eab308",
    tab: "#bfdbfe",
    gradient:
      "linear-gradient(-45deg, #5BCEFA, #5BCEFA, #ffffff, #ffffff, #F5A9B8, #F5A9B8)",
  },
  {
    name: "lesbian",
    label: "Lesbian",
    dark: false,
    color: "#000000",
    secondary: "#ffffff",
    background: "#ffffff",
    star: "#fd9855",
    tab: "#bfdbfe",
    gradient:
      "linear-gradient(45deg, #d42c00, #fd9855, #ffffff, #ffffff, #d161a2, #a20161)",
  },
  {
    name: "bisexual",
    label: "Bisexual",
    dark: true,
    color: "#ffffff",
    secondary: "#bae6fd",
    background: "#000000",
    star: "#D60270",
    tab: "#0038A8",
    gradient: "linear-gradient(45deg, #D60270, #9B4F96, #0038A8)",
  },
  {
    name: "maine",
    label: "Maine",
    dark: false,
    color: "#00512C",
    secondary: "#3B3C6E",
    background: "#EDE8CE",
    star: "#3B3C6E",
    tab: "#bfdbfe",
  },
];

export default THEMES;
